<?php

namespace ContestBundle\Repository;

/**
 * UniversityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversityRepository extends \Doctrine\ORM\EntityRepository
{
}
